/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "kds_rpc.h"

bool_t
xdr_key_request (XDR *xdrs, key_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, MAXNAMELEN))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_key_rtn (XDR *xdrs, key_rtn *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 100))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	return TRUE;
}
