/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _KDS_RPC_H_RPCGEN
#define _KDS_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 4096

struct key_request {
	char *filename;
	int x;
	int y;
};
typedef struct key_request key_request;

struct key_rtn {
	char *key;
	int err;
};
typedef struct key_rtn key_rtn;

#define KDS_RPC 22855
#define KEYREQVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define KEYREQ 1
extern  struct key_rtn * keyreq_1(struct key_request *, CLIENT *);
extern  struct key_rtn * keyreq_1_svc(struct key_request *, struct svc_req *);
extern int kds_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define KEYREQ 1
extern  struct key_rtn * keyreq_1();
extern  struct key_rtn * keyreq_1_svc();
extern int kds_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_key_request (XDR *, key_request*);
extern  bool_t xdr_key_rtn (XDR *, key_rtn*);

#else /* K&R C */
extern bool_t xdr_key_request ();
extern bool_t xdr_key_rtn ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_KDS_RPC_H_RPCGEN */
